name: Build

on:
  workflow_dispatch:

jobs:
  foonahan_memory:
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        platform: [ubuntu-24.04]

    runs-on: ${{ matrix.platform }}

    steps:
    - name: Clone external project
      run: |
        ls -al
        
